# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aL8xT2nlcvLTmgAIGe60gVqUY1H4ZU7I
"""

ls

import pandas as pd
path = "/content/students.txt"
df = pd.read_csv(path, header=None, names=["Name", "Score"])
print(df)

names = df["Name"].tolist()
scores = df["Score"].tolist()
print(names , scores)

max_score = df["Score"].max()
max_name = df.loc[df["Score"].idxmax(), "Name"]

min_score = df["Score"].min()
min_name = df.loc[df["Score"].idxmin(), "Name"]

average_score = df["Score"].mean()

print(max_score, max_name)
print(min_score, min_name)
print(average_score)